# Generated by Django 5.2.7 on 2026-02-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=200)),
                ('batch_number', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('description', models.TextField()),
                ('side_effects', models.TextField()),
            ],
        ),
    ]
