# Generated by Django 5.0.1 on 2026-02-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_userprofile_phone_userprofile_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='risk_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='scan_count',
            field=models.IntegerField(default=0),
        ),
    ]
