# Generated by Django 5.2.7 on 2026-03-07 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userprofile_risk_count_userprofile_scan_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(blank=True, max_length=200, null=True)),
                ('authenticity', models.CharField(blank=True, max_length=50, null=True)),
                ('authenticity_confidence', models.FloatField(blank=True, null=True)),
                ('risk_level', models.CharField(blank=True, max_length=50, null=True)),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scan_date'],
            },
        ),
    ]
